application_name: Test Application

# API Key Repository Configuration for Firestore Testing
api_key_repository:
  type: firestore
  pseudonymization_salt: test_salt_for_firestore_testing
  firestore:
    project_id: test-project-id
    collection_name: test_api_keys

# Minimal config for testing
default_models:
  chat: ""
  vision: ""
  embeddings: ""

models: []
embeddings: []
knowledge_pack_path: "./"
enabled_providers: [] 